package com.sower.rdbms.pojo;
// default package
// Generated 15 Jun, 2017 8:22:38 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long addressId;
	private String city;
	private String state;
	private String country;
	private long zipcode;
	private Date createdDate;
	private Date updatedDate;
	private char isDeleted;

	public Address() {
	}

	public Address(String city, String state, String country, long zipcode,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(long zipcode) {
		this.zipcode = zipcode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
