package com.sower.rdbms.pojo;

// default package
// Generated 13 Jun, 2017 5:10:22 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long categoryId;
	private String categoryName;
	private String displayCategoryName;
	private String categoryDescrption;
	private Date createdDate;
	private Date updatedDate;
	private char isDeleted;
	private Long createdUserId;
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public Category() {
	}

	public Category(String categoryName, String displayCategoryName,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.categoryName = categoryName;
		this.displayCategoryName = displayCategoryName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public Category(String categoryName, String displayCategoryName,
			String categoryDescrption, Date createdDate, Date updatedDate,
			char isDeleted, Long createdUserId, Set<Questions> questionses) {
		this.categoryName = categoryName;
		this.displayCategoryName = displayCategoryName;
		this.categoryDescrption = categoryDescrption;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
		this.createdUserId = createdUserId;
		this.questionses = questionses;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getDisplayCategoryName() {
		return this.displayCategoryName;
	}

	public void setDisplayCategoryName(String displayCategoryName) {
		this.displayCategoryName = displayCategoryName;
	}

	public String getCategoryDescrption() {
		return this.categoryDescrption;
	}

	public void setCategoryDescrption(String categoryDescrption) {
		this.categoryDescrption = categoryDescrption;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

}
