package com.sower.rdbms.pojo;

// default package
// Generated 13 Jun, 2017 5:10:22 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long questionId;
	private User user;
	private Category category;
	private String displayQuestion;
	private String questionDescription;
	private char isRadio;
	private String summary;
	private Date createdDate;
	private Date updatedDate;
	private char isDeleted;

	public Questions() {
	}

	public Questions(Category category, String displayQuestion, char isRadio,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.category = category;
		this.displayQuestion = displayQuestion;
		this.isRadio = isRadio;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public Questions(User user, Category category, String displayQuestion,
			String questionDescription, char isRadio, String summary,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.user = user;
		this.category = category;
		this.displayQuestion = displayQuestion;
		this.questionDescription = questionDescription;
		this.isRadio = isRadio;
		this.summary = summary;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getDisplayQuestion() {
		return this.displayQuestion;
	}

	public void setDisplayQuestion(String displayQuestion) {
		this.displayQuestion = displayQuestion;
	}

	public String getQuestionDescription() {
		return this.questionDescription;
	}

	public void setQuestionDescription(String questionDescription) {
		this.questionDescription = questionDescription;
	}

	public char getIsRadio() {
		return this.isRadio;
	}

	public void setIsRadio(char isRadio) {
		this.isRadio = isRadio;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

}
