package com.sower.rdbms.pojo;

// default package
// Generated 4 Jun, 2017 2:12:18 PM by Hibernate Tools 4.0.0

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;

	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
