package com.sower.rdbms.pojo;

// default package
// Generated 4 Jun, 2017 4:15:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAccess generated by hbm2java
 */
public class UserAccess implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long accessId;
	private String accessName;
	private String accessDisplayName;
	private String accessDescription;
	private Date createdDate;
	private Date updatedDate;
	private char isDeleted;
	private Set<User> users = new HashSet<User>(0);

	public UserAccess() {
	}

	public UserAccess(String accessName, String accessDisplayName,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.accessName = accessName;
		this.accessDisplayName = accessDisplayName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public UserAccess(String accessName, String accessDisplayName,
			String accessDescription, Date createdDate, Date updatedDate,
			char isDeleted, Set<User> users) {
		this.accessName = accessName;
		this.accessDisplayName = accessDisplayName;
		this.accessDescription = accessDescription;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
		this.users = users;
	}

	public Long getAccessId() {
		return this.accessId;
	}

	public void setAccessId(Long accessId) {
		this.accessId = accessId;
	}

	public String getAccessName() {
		return this.accessName;
	}

	public void setAccessName(String accessName) {
		this.accessName = accessName;
	}

	public String getAccessDisplayName() {
		return this.accessDisplayName;
	}

	public void setAccessDisplayName(String accessDisplayName) {
		this.accessDisplayName = accessDisplayName;
	}

	public String getAccessDescription() {
		return this.accessDescription;
	}

	public void setAccessDescription(String accessDescription) {
		this.accessDescription = accessDescription;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
