package com.sower.rdbms.pojo;
// default package
// Generated 13 Jun, 2017 7:09:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long userId;
	private UserAccess userAccess;
	private String firstName;
	private String lastName;
	private String emailId;
	private long mobile;
	private Date dob;
	private String userName;
	private String password;
	private String city;
	private String state;
	private String country;
	private long zipcode;
	private Date createdDate;
	private Date updatedDate;
	private char isDeleted;
	private Long createdUserId;
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public User() {
	}

	public User(UserAccess userAccess, String firstName, String lastName,
			long mobile, Date dob, String userName, String password,
			String city, String state, String country, long zipcode,
			Date createdDate, Date updatedDate, char isDeleted) {
		this.userAccess = userAccess;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobile = mobile;
		this.dob = dob;
		this.userName = userName;
		this.password = password;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public User(UserAccess userAccess, String firstName, String lastName,
			String emailId, long mobile, Date dob, String userName,
			String password, String city, String state, String country,
			long zipcode, Date createdDate, Date updatedDate, char isDeleted,
			Long createdUserId, Set<Questions> questionses) {
		this.userAccess = userAccess;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.mobile = mobile;
		this.dob = dob;
		this.userName = userName;
		this.password = password;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
		this.createdUserId = createdUserId;
		this.questionses = questionses;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public UserAccess getUserAccess() {
		return this.userAccess;
	}

	public void setUserAccess(UserAccess userAccess) {
		this.userAccess = userAccess;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public long getMobile() {
		return this.mobile;
	}

	public void setMobile(long mobile) {
		this.mobile = mobile;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(long zipcode) {
		this.zipcode = zipcode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

}
