CREATE DATABASE IF NOT EXISTS SOWER;

USE SOWER;

CREATE TABLE IF NOT EXISTS `USER_ACCESS` (
	`ACCESS_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`ACCESS_NAME` VARCHAR(15) NOT NULL,
	`ACCESS_DISPLAY_NAME` VARCHAR(15) NOT NULL,
	`ACCESS_DESCRIPTION` VARCHAR(500) NULL DEFAULT NULL,
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ACCESS_ID`) USING BTREE
)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `USER` (
	`USER_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(50) NOT NULL,
	`LAST_NAME` VARCHAR(50) NOT NULL,
	`EMAIL_ID` VARCHAR(100) NULL DEFAULT NULL,
	`MOBILE` BIGINT(12) NOT NULL,
	`DOB` TIMESTAMP NOT NULL,
	`ACCESS_ID` BIGINT(10) NOT NULL,
	`USER_NAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(50) NOT NULL,
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	PRIMARY KEY (`USER_ID`) USING BTREE,
	KEY `FK_ACCESS_ID` (`ACCESS_ID`),
	CONSTRAINT `FK_ACCESS_ID` FOREIGN KEY (`ACCESS_ID`) REFERENCES USER_ACCESS(`ACCESS_ID`)
	ON DELETE CASCADE ON UPDATE CASCADE
)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;