CREATE TABLE IF NOT EXISTS `CATEGORY` (
	`CATEGORY_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CATEGORY_NAME` VARCHAR(50) NOT NULL,
	`DISPLAY_CATEGORY_NAME` VARCHAR(50) NOT NULL,
	`CATEGORY_DESCRPTION` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	`CREATED_USER_ID` BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`CATEGORY_ID`) USING BTREE
)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `QUESTIONS` (
	`QUESTION_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CATEGORY_ID` BIGINT(10) NOT NULL,
	`DISPLAY_QUESTION` VARCHAR(50) NOT NULL,
	`QUESTION_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL,
	`IS_RADIO` CHAR NOT NULL DEFAULT 'Y',
	`SUMMARY` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	`CREATED_USER_ID` BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`QUESTION_ID`) USING BTREE,
	KEY `FK_CATEGORY_ID` (`CATEGORY_ID`),
	KEY `FK_CREATED_USER_ID` (`CREATED_USER_ID`),
	CONSTRAINT `FK_CREATED_USER_ID` FOREIGN KEY (`CREATED_USER_ID`) REFERENCES USER(`USER_ID`)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT `FK_CATEGORY_ID` FOREIGN KEY (`CATEGORY_ID`) REFERENCES CATEGORY(`CATEGORY_ID`)
	ON DELETE CASCADE ON UPDATE CASCADE
	)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;