CREATE TABLE IF NOT EXISTS `CATEGORY` (
	`CATEGORY_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CATEGORY_NAME` VARCHAR(50) NOT NULL,
	`DISPLAY_CATEGORY_NAME` VARCHAR(50) NOT NULL,
	`CATEGORY_DESCRPTION` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	`CREATED_USER_ID` BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`CATEGORY_ID`) USING BTREE
)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `QUESTIONS` (
	`QUESTION_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CATEGORY_ID` BIGINT(10) NOT NULL,
	`DISPLAY_QUESTION` VARCHAR(1000) NOT NULL,
	`QUESTION_DESCRIPTION` VARCHAR(1000) NULL DEFAULT NULL,
	`IS_RADIO` CHAR NOT NULL DEFAULT 'Y',
	`DISPLAY_SUMMARY` CHAR NOT NULL DEFAULT 'Y',
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	`CREATED_USER_ID` BIGINT(10) NULL DEFAULT NULL,
	`USER_TYPE` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`QUESTION_ID`) USING BTREE,
	KEY `FK_CATEGORY_ID` (`CATEGORY_ID`),
	CONSTRAINT `FK_CATEGORY_ID` FOREIGN KEY (`CATEGORY_ID`) REFERENCES CATEGORY(`CATEGORY_ID`)
	ON DELETE CASCADE ON UPDATE CASCADE
	)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `SOLUTIONS` (

	`SOULTION_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`QUESTIONER_ID` BIGINT(10) NOT NULL ,
	`USER_ID` BIGINT(10) NOT NULL ,
	`QUESTION_ID` BIGINT(10) NOT NULL,
	
	`RADIO_VALUE` CHAR NULL DEFAULT 'Y',
	`COMMENT_VALUE` VARCHAR(4000) NULL DEFAULT NULL,
	
	`CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`IS_DELETED` CHAR NOT NULL DEFAULT 'N',
	
	PRIMARY KEY (`SOULTION_ID`) USING BTREE
	)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=1;

